#ifndef __FAIRY_GAMES_GARDEN_RUSH_ENUMS_H
#define __FAIRY_GAMES_GARDEN_RUSH_ENUMS_H


enum PlantTypeNeighborType
{
	// neutral must be zero
	NEIGHBOR_NEUTRAL = 0,
	NEIGHBOR_GOOD = 1,
	NEIGHBOR_REALLY_GOOD = 2,
	NEIGHBOR_BAD = 4,
	NEIGHBOR_ERROR = 7
};


enum PlantTypePhasisView
{
	PLANT_PHASIS_SEED,
	PLANT_PHASIS_SEEDED,
	PLANT_PHASIS_GROWTH_1,
	PLANT_PHASIS_GROWTH_2,
	PLANT_PHASIS_GROWTH_3,
	PLANT_PHASIS_GROWTH_4,
	PLANT_PHASIS_GROWTH_5,
	PLANT_PHASIS_FINAL_NEUTRAL,
	PLANT_PHASIS_FINAL_GOOD,
	PLANT_PHASIS_FINAL_VERY_GOOD,
	PLANT_PHASIS_FINAL_BAD,
	PLANT_PHASIS_SIZE,
	PLANT_PHASIS_ERROR
};

enum GridNodeType {
	GRID_NODE_NONE,
	GRID_NODE_2D,
	GRID_NODE_ISO,
	GRID_NODE_3D
};

#endif // __FAIRY_GAMES_GARDEN_RUSH_ENUMS_H